# Generated by Django 6.0.8 on 2026-09-05 01:13

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='loc', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('location_type', models.CharField(blank=True, help_text='e.g. site, field, block, greenhouse, nursery, collection point', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-3', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
