# Generated by Django 6.0.8 on 2026-09-05 01:13

import django.db.models.deletion
import prefix_id.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='crop', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Germplasm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=25, prefix='gp', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('germplasm_type', models.CharField(choices=[('WILD_COLLECTION', 'Wild collection'), ('LANDRACE', 'Landrace'), ('CULTIVAR', 'Cultivar / released variety'), ('BREEDING_POPULATION', 'Breeding population'), ('SYNTHETIC', 'Synthetic'), ('FAMILY', 'Family (cross progeny)'), ('INBRED_LINE', 'Inbred line'), ('GENETIC_STOCK', 'Genetic stock'), ('NAMED_CLONE', 'Named clone'), ('HYBRID', 'Hybrid'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('material_use', models.CharField(choices=[('SCION', 'Scion'), ('ROOTSTOCK', 'Rootstock'), ('BOTH', 'Both'), ('NA', 'Not applicable')], default='NA', help_text='Orthogonal to germplasm_type; flags rootstock vs scion material.', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OBSOLETE', 'Obsolete'), ('DISCARDED', 'Discarded'), ('MERGED', 'Merged into another record')], default='ACTIVE', max_length=15)),
                ('source_type', models.CharField(choices=[('INTERNAL_CROSS', 'Internal cross'), ('INTERNAL_SELECTION', 'Internal selection'), ('EXTERNAL_ACCESSION', 'External accession'), ('WILD_COLLECTION', 'Wild collection'), ('DONATION', 'Donation'), ('PURCHASE', 'Purchase'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=25)),
                ('source_institute', models.CharField(blank=True, max_length=200)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('donor', models.CharField(blank=True, max_length=200)),
                ('biological_status', models.CharField(blank=True, choices=[('WILD', 'Wild (100)'), ('WEEDY', 'Weedy (200)'), ('LANDRACE', 'Landrace (300)'), ('BREEDING_MATERIAL', 'Breeding/research material (400)'), ('ADVANCED_CULTIVAR', 'Advanced / improved cultivar (500)'), ('GENETIC_STOCK', 'Genetic stock (600)'), ('OTHER', 'Other (999)')], max_length=25)),
                ('origin_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-3', max_length=3)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('collector', models.CharField(blank=True, max_length=200)),
                ('passport', models.JSONField(blank=True, default=dict, help_text='Full MCPD record as imported.')),
                ('pedigree_string', models.TextField(blank=True, help_text='Free-text (Purdy) pedigree; import artifact.')),
                ('notes', models.TextField(blank=True)),
                ('collecting_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_germplasm', to='locations.location')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Set when this record is a duplicate folded into another.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='germplasm.germplasm')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='germplasm', to='core.program')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=25, prefix='gt', primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('origin', models.CharField(choices=[('SEEDLING', 'Seedling'), ('CLONAL_SELECTION', 'Clonal selection'), ('LANDRACE_SELECTION', 'Landrace selection'), ('MUTATION', 'Mutation / sport'), ('DOUBLED_HAPLOID', 'Doubled haploid'), ('INTROGRESSION', 'Introgression line'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OBSOLETE', 'Obsolete'), ('DISCARDED', 'Discarded'), ('MERGED', 'Merged into another record')], default='ACTIVE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('clonal_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clonal_descendants', to='germplasm.genotype')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_genotypes', to=settings.AUTH_USER_MODEL)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genotypes', to='germplasm.germplasm')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GermplasmList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='gpl', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('list_type', models.CharField(choices=[('CROSSING_BLOCK', 'Crossing block'), ('PANEL', 'Panel'), ('TRAINING_SET', 'Training set'), ('NURSERY', 'Nursery'), ('TRIAL_ENTRIES', 'Trial entries'), ('WORKING_SET', 'Working set'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='germplasm_lists', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='germplasm_lists', to='core.program')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GermplasmListItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='gpli', primary_key=True, serialize=False, unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='germplasm.germplasm')),
                ('germplasm_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='germplasm.germplasmlist')),
            ],
            options={
                'ordering': ['germplasm_list', 'position'],
            },
        ),
        migrations.CreateModel(
            name='GermplasmName',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='gpn', primary_key=True, serialize=False, unique=True)),
                ('name_type', models.CharField(choices=[('BREEDER_CODE', 'Breeder code'), ('ACCESSION_NUMBER', 'Accession number'), ('PI_NUMBER', 'USDA PI number'), ('GRIN_ID', 'GRIN identifier'), ('CULTIVAR_NAME', 'Cultivar name'), ('NICKNAME', 'Nickname / working name'), ('DOI', 'DOI'), ('OTHER', 'Other')], max_length=20)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('namespace', models.CharField(blank=True, help_text='Owning institution / registry.', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='germplasm.germplasm')),
            ],
            options={
                'ordering': ['germplasm', 'name_type'],
            },
        ),
        migrations.CreateModel(
            name='Parentage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='par', primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('FEMALE', 'Female / seed parent'), ('MALE', 'Male / pollen parent'), ('RECURRENT', 'Recurrent parent'), ('DONOR', 'Donor parent'), ('OPEN_POLLINATED', 'Open-pollinated (pollen cloud)'), ('SELF', 'Self'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='germplasm.germplasm')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_edges', to='germplasm.germplasm')),
                ('parent_genotype', models.ForeignKey(blank=True, help_text='The specific parent genotype, when known (crossing-block clone).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentage_edges', to='germplasm.genotype')),
            ],
            options={
                'ordering': ['child', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='plt', primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(db_index=True, max_length=100)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('propagation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ALIVE', 'Alive'), ('DEAD', 'Dead'), ('REMOVED', 'Removed'), ('MISSING', 'Missing'), ('UNKNOWN', 'Unknown')], default='ALIVE', max_length=15)),
                ('removal_date', models.DateField(blank=True, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='locations.location')),
                ('parent_plant', models.ForeignKey(blank=True, help_text='Plant this one was divided / propagated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propagules', to='germplasm.plant')),
                ('primary_genotype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='germplasm.genotype')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PlantComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='pcmp', primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('ROOTSTOCK', 'Rootstock'), ('INTERSTEM', 'Interstem'), ('SCION', 'Scion'), ('OWN_ROOT', 'Own root')], max_length=12)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='0 = rootstock, ascending; multiple scions allowed.')),
                ('propagation_method', models.CharField(choices=[('GRAFT', 'Graft'), ('CHIP_BUD', 'Chip budding'), ('T_BUD', 'T-budding'), ('CUTTING', 'Cutting'), ('DIVISION', 'Division'), ('SEEDLING', 'Seedling'), ('TISSUE_CULTURE', 'Tissue culture'), ('LAYERING', 'Layering'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('grafted_on', models.DateField(blank=True, null=True)),
                ('removed_on', models.DateField(blank=True, help_text='Set when top-worked over / removed.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='germplasm.plant')),
                ('propagated_from', models.ForeignKey(blank=True, help_text='Source plant of the scion wood / cutting / division.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propagated_components', to='germplasm.plant')),
                ('source_genotype', models.ForeignKey(blank=True, help_text='Null = a seedling of source_germplasm, genotype not yet minted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_components', to='germplasm.genotype')),
                ('source_germplasm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_components', to='germplasm.germplasm')),
            ],
            options={
                'ordering': ['plant', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PopulationDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='popd', primary_key=True, serialize=False, unique=True)),
                ('cycle_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cycle_label', models.CharField(blank=True, help_text='e.g. "C3"', max_length=20)),
                ('mating_design', models.CharField(blank=True, choices=[('POLYCROSS', 'Polycross'), ('HALF_DIALLEL', 'Half diallel'), ('FULL_DIALLEL', 'Full diallel'), ('NC1', 'North Carolina I'), ('NC2', 'North Carolina II'), ('LINE_BY_TESTER', 'Line × tester'), ('OPEN_POLLINATED', 'Open-pollinated'), ('MASS_SELECTION', 'Mass selection'), ('SINGLE_CROSS', 'Single cross'), ('THREE_WAY', 'Three-way cross'), ('BACKCROSS', 'Backcross'), ('OTHER', 'Other')], max_length=20)),
                ('effective_size', models.PositiveIntegerField(blank=True, help_text='Ne', null=True)),
                ('num_parents', models.PositiveIntegerField(blank=True, null=True)),
                ('selection_method', models.CharField(blank=True, max_length=120)),
                ('selection_intensity', models.DecimalField(blank=True, decimal_places=2, help_text='percent', max_digits=5, null=True)),
                ('base_population', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_populations', to='germplasm.germplasm')),
                ('germplasm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='population_detail', to='germplasm.germplasm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='txn', primary_key=True, serialize=False, unique=True)),
                ('genus', models.CharField(max_length=120)),
                ('species', models.CharField(blank=True, max_length=120)),
                ('subtaxon_rank', models.CharField(blank=True, help_text='subsp., var., f., ...', max_length=20)),
                ('subtaxon_name', models.CharField(blank=True, max_length=120)),
                ('authority', models.CharField(blank=True, max_length=200)),
                ('common_name', models.CharField(blank=True, max_length=120)),
                ('ploidy', models.CharField(blank=True, help_text='e.g. "2n=6x=42"', max_length=30)),
                ('mating_system', models.CharField(choices=[('SELF', 'Self-pollinating'), ('CROSS', 'Cross-pollinating'), ('MIXED', 'Mixed mating'), ('APOMICT', 'Apomictic'), ('CLONAL', 'Clonally propagated'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('growth_habit', models.CharField(blank=True, choices=[('HERB', 'Herbaceous'), ('GRAMINOID', 'Graminoid'), ('SHRUB', 'Shrub'), ('TREE', 'Tree'), ('VINE', 'Vine / liana'), ('OTHER', 'Other')], max_length=10)),
                ('is_perennial', models.BooleanField(default=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxa', to='germplasm.crop')),
            ],
            options={
                'verbose_name_plural': 'taxa',
                'ordering': ['genus', 'species', 'subtaxon_name'],
            },
        ),
        migrations.AddField(
            model_name='germplasm',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='germplasm', to='germplasm.taxon'),
        ),
        migrations.AddConstraint(
            model_name='genotype',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_genotype_code'),
        ),
        migrations.AddConstraint(
            model_name='germplasmlistitem',
            constraint=models.UniqueConstraint(fields=('germplasm_list', 'germplasm'), name='uniq_list_membership'),
        ),
        migrations.AddConstraint(
            model_name='germplasmname',
            constraint=models.UniqueConstraint(fields=('name_type', 'value', 'namespace'), name='uniq_germplasm_name'),
        ),
        migrations.AddConstraint(
            model_name='germplasmname',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('germplasm',), name='uniq_primary_name_per_germplasm'),
        ),
        migrations.AddIndex(
            model_name='parentage',
            index=models.Index(fields=['parent'], name='germplasm_p_parent__483ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='parentage',
            index=models.Index(fields=['child'], name='germplasm_p_child_i_850d3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentage',
            constraint=models.UniqueConstraint(fields=('child', 'parent', 'role'), name='uniq_parentage_edge'),
        ),
        migrations.AddConstraint(
            model_name='parentage',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'FEMALE')), fields=('child',), name='uniq_female_parent_per_child'),
        ),
        migrations.AddConstraint(
            model_name='parentage',
            constraint=models.CheckConstraint(condition=models.Q(('child', models.F('parent')), _negated=True), name='parentage_no_self_loop'),
        ),
        migrations.AddConstraint(
            model_name='plantcomponent',
            constraint=models.UniqueConstraint(fields=('plant', 'role', 'position'), name='uniq_component_slot'),
        ),
        migrations.AddConstraint(
            model_name='taxon',
            constraint=models.UniqueConstraint(fields=('genus', 'species', 'subtaxon_rank', 'subtaxon_name'), name='unique_taxon_name'),
        ),
        migrations.AddIndex(
            model_name='germplasm',
            index=models.Index(fields=['germplasm_type'], name='germplasm_g_germpla_76c0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='germplasm',
            index=models.Index(fields=['status'], name='germplasm_g_status_9e0735_idx'),
        ),
    ]
