# Generated by Django 6.0.8 on 2026-09-05 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentage',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Null only when role=OPEN_POLLINATED (no single identifiable parent).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_edges', to='germplasm.germplasm'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='mating_system',
            field=models.CharField(choices=[('SELF', 'Self-pollinating'), ('CROSS', 'Cross-pollinating'), ('MIXED', 'Mixed mating'), ('APOMICT', 'Apomictic'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='parentage',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OPEN_POLLINATED')), fields=('child',), name='uniq_open_pollinated_per_child'),
        ),
        migrations.AddConstraint(
            model_name='parentage',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'OPEN_POLLINATED'), ('parent__isnull', False), _connector='OR'), name='parentage_parent_required_unless_open_pollinated'),
        ),
    ]
