# Generated by Django 6.0.8 on 2026-09-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0002_alter_parentage_parent_alter_taxon_mating_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentage',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Null only for role=OPEN_POLLINATED (no identifiable parent).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_edges', to='germplasm.germplasm'),
        ),
    ]
